### ISSUE TITLE
Recommended Note

### ISSUE THREAD

**Issue by seanturner** [tlswg/rfc8447bis#20]
Currently the I-D includes the following note:

    Note:
    : If an item is not marked as "Recommended", it does not
    necessarily mean that it is flawed; rather, it indicates that the
    item either has not been through the IETF consensus process, has
    limited applicability, or is intended only for specific use cases.

Now that we have three values do we need to expand this to also include "D".

**Comment by jsalowey** [comment]
Proposed text in PR #30
