### ISSUE TITLE
Could this document update instead of obsolete RFC8447

### ISSUE THREAD

**Issue by jsalowey** [tlswg/rfc8447bis#31]
Obsoleting RFC 8447 means duplicating a lot of text and making changes to it which makes the document have awkward wording and makes the changes difficult to follow.   I think it would be clearer if it were an update and just listed the changes.  see Extension Types PR #30

**Comment by seanturner** [comment]
At IETF 115, there was general agreement that this document could be an update as opposed to an obsolete to make it easier on IANA.
