### ISSUE TITLE
Deprecate Curves

### ISSUE THREAD

**Issue by seanturner** [tlswg/rfc8447bis#41]
Need make some curves with a "D" in the recommended column.  How about we start with anything smaller that 256?  More specifically these:

| Value | Description | DTLS-OK | Current value for Recommended | Ref|CHANGE|
|-:|:-: |:-: |:-: |:-:|:-:|
| 1 |sect163k1 | Y | N | [RFC8422] | N->D
2 | sect163r1 | Y | N | [RFC8422] |  N->D
3 | sect163r2 | Y | N | [RFC8422] |  N->D
4 | sect193r1 | Y | N | [RFC8422] |  N->D
5 | sect193r2 | Y | N | [RFC8422] |  N->D
6 | sect233k1 | Y | N | [RFC8422] |  N->D
7 | sect233r1 | Y | N | [RFC8422] |  N->D
8 | sect239k1 | Y | N | [RFC8422] |  N->D
15 | secp160k1 | Y | N | [RFC8422] |  N->D
16 | secp160r1 | Y | N | [RFC8422] |  N->D
17 | secp160r2 | Y | N | [RFC8422] |  N->D
18 | secp192k1 | Y | N | [RFC8422] |  N->D
19 | secp192r1 | Y | N | [RFC8422] |  N->D
20 | secp224k1 | Y | N | [RFC8422] |  N->D
21 | secp224r1  | Y | N | [RFC8422] |  N->D

**Comment by seanturner** [comment]
This lines up with @emanjon was suggesting in [NULL Encryption and Key Exchange Without Forward Secrecy are Discouraged](https://github.com/emanjon/draft-mattsson-tls-psk-ke-dont-dont-dont).  But he also included:

| Value | Description | DTLS-OK | Current value for Recommended | Ref|CHANGE|
|-:|:-: |:-: |:-: |:-:|:-:|
|256 | ffdhe2048 | Y | N | [RFC7919]| N->D |

**Comment by jsalowey** [comment]
ffdhe2048 might be something for the keyex draft.
