### ISSUE TITLE
Add  "For TLS 1.3 or later" column

### ISSUE THREAD

**Issue by seanturner** [tlswg/rfc8447bis#47]
Based on discussions at IETF 115 on draft-rsalz-tls-tls12-frozen.

**Comment by richsalz** [comment]
I think we really want the field called "Comments"

**Comment by seanturner** [comment]
Ah ... okay some of the non-orphaned registries already have a "Comment" column, but we can add that column to the others. I'll probably skip [ExtensionType](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#tls-extensiontype-values-1) because it already has a "TLS 1.3 column". Ah and "TLS Exporter Labels" also seems to have a "Note" column.

**Comment by richsalz** [comment]
I wouldn’t skip ExtensionType, because the TLS 1.3 column only shows where things can appear. There’s no room to say “Not for TLS 1.2 or earlier” in that table.

**Comment by seanturner** [comment]
I revised PR #48.
