### ISSUE TITLE
Section 15 ambiguity

### ISSUE THREAD

**Issue by richsalz** [tlswg/rfc8447bis#53]
I'm not sure how to interpret this final sentence of section 15: "For this reason, designated experts should decline code point registrations for documents which have already been adopted or are being proposed for adoption by IETF working groups or IRTF research groups."  

Do you mean to add "other than TLS" at the end?

**Comment by richsalz** [comment]
And do you also mean the DE's should verify/ensure/check/something that there is consensus within TLSWG to do that?

**Comment by ekr** [comment]
I don't think this should say other than TLS. The basic sense here is that if the document is being worked in in the I[ER]TF or proposed for being worked on in in the I[ER]TF, then they shouldn't also be pursuing independent code point assignment via the experts, except if the TLS WG signs off.
